### PR TITLE
Dkz fix typo

### PR DESCRIPTION
**Pull request by dokenzy**

### CODE REVIEW

**Comment by rstoenescu** [comment]
Hi, there's a merge conflict.

**Comment by rstoenescu** [comment]
Can you git pull and try again, pls?

**Comment by dokenzy** [comment]
On 'dev' branch, I can't find css-icons.md and 'api' directory doesn't exist
Could you check this?

**Comment by rstoenescu** [comment]
Yes, because work is in progress for v0.14 and the folder structure and files have changed. Always do a git pull before submitting, otherwise we are going to bump into merge errors.
Resolved the errors and merged.

Thank you so much for your efforts!

**Comment by rstoenescu** [comment]
Looking forward to more PRs from you. And congrats for your first! If you bump into trouble, contact me on Gitter so I can help you out.

**Pull request merged**
