### PR TITLE
Update lists-and-list-items.md

### PR DESCRIPTION
**Pull request by olegvakulenko**
1. "Render with specific HTML tag" - possibility of usage custom attributes with tag;
2. Example of list with <a> tag.
Could you please edit my explanation if needed?
Thanks!

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [ ] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] It's submitted to the `dev` branch and _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested with all major browsers

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by rstoenescu** [comment]
Thanks.

**Comment by olegvakulenko** [comment]
Could you please tell me, is you disagreed with my PR?
Or this is strange, but I can't see updated text.

**Comment by rstoenescu** [comment]
I thought a bit about it. It may send the wrong idea, especially for people coming from the server-side, that this is the way to really do the navigation in your app, instead of using Vue Router. Your addition is great, don't get me wrong, but just don't want to send mixed signals to beginners.

**Comment by olegvakulenko** [comment]
Yes, I understand you. But in my case, when I use UMD version of Quasar, I don't use Vue Router and all navigation build on links. And my PR helps make whole menu item clickable. Or I just don't found right solution for do this.
Thanks for explanation.

**Pull request merged**
