### PR TITLE
remove the word JavaScript from the PWA cache reference

### PR DESCRIPTION
**Pull request by genyded**
PWA cache can store images, css, PDF's, or just about any file type so to say it's just JS is not correct.

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [x] Provided documentation update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch and _not_ the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] It's been tested with all major browsers

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by rstoenescu** [comment]
It does say "only Javascript and JSON files". But anyway, if there's room to make it extra clear, then it's good.
Thanks for doing a PR!

**Comment by nothingismagick** [comment]
@genyded - Saw that you've been answering a lot of questions on our forum. If that's your thing, I really recommend that you check out our Discord server!

**Comment by genyded** [comment]
Ya, I have bit I find discord very distracting.

**Comment by nothingismagick** [comment]
Well I find it useful for coordination, but I know what you mean.

**Pull request merged**
