### PR TITLE
Update ajax-requests.md

### PR DESCRIPTION
**Pull request by mstaack**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [x] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] It's submitted to the `dev` branch and _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested with all major browsers

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by rstoenescu** [comment]
Thanks for this!

**Comment by mstaack** [comment]
your welcome... i am not the frontend expert...but will help beginners to quickstart ;)

**Comment by mstaack** [comment]
@rstoenescu always to dev branch?

**Comment by rstoenescu** [comment]
Yes, merged it. Changes will be visible when v0.14 is released.

**Comment by mstaack** [comment]
looking forward!

**Pull request merged**
