### PR TITLE
Update transition.md

### PR DESCRIPTION
**Pull request by null99**
The text references "both" examples, the keyword appear was actually only on one example.

**What kind of change does this PR introduce?** (check at least one)

- [] Bugfix
- [ ] Feature
- [ ] Code style update
- [x] Provided documentation update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] It's submitted to the `dev` branch and _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested with all major browsers

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by rstoenescu** [comment]
Hi, yes, but this is irrelevant to the subject.

**Comment by null99** [comment]
Sorry, I haven't used Github a long time and don't get what you mean.

**Comment by rstoenescu** [comment]
No, I mean the actual usage. "appear" property is irrelevant to the examples in docs.

**Comment by null99** [comment]
Thanks for the clarification. So, shouldn't at least the text "**Both** examples above have the Boolean property appear specified, (...)" be updated to reflect the actual situation, because - as I see it - not both examples have that keyword specified, as the text suggests.

**Comment by rstoenescu** [comment]
Uh oh. I'm the one that missed that one out. The PR is correct. Sorry for all the "fuss" and thanks for contributing!

**Pull request merged**
