### PR TITLE
docs (layout): custom component as layout slot

### PR DESCRIPTION
**Pull request by kailniris**
add hint for possibility to use custom components as layout slots
add example how to use custom components as layout slots

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:
- [x] docs

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch and _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] It's been tested with all major browsers

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**
https://gitter.im/quasarframework/Lobby?at=5950c8fe57a6e9f72efd4050

### CODE REVIEW

**Comment by rstoenescu** [comment]
Isn't this obvious?

**Comment by kailniris** [comment]
It was not obvious for me during first use of layouts.

And this note can be misunderstood:

> IMPORTANT
> The slots must be direct children of <q-layout> (do not wrap them with any DOM elements / components) otherwise Vue won’t pick them up. Read about Vue content distribution with slots to understand why.

This one example I added clarify it even for beginner Vue users whose don't yet know how slots work.

**Comment by rstoenescu** [comment]
Thanks for taking time for a PR and wanting to improve things!

**Comment by smolinari** [comment]
I'm a bit of a noob too and this simple tip is sort of an eye opener. 😄 

Scott

**Pull request merged**
