### PR TITLE
Dev fix typo

### PR DESCRIPTION
**Pull request by dokenzy**

### CODE REVIEW

**Comment by rstoenescu** [comment]
Hi, this has been taken care of by my merge error fixes earlier. So, already included in your previous PR.

**Comment by dokenzy** [comment]
I don't understand why another files was included. Is PR is right?

**Comment by rstoenescu** [comment]
Here is the full procedure for making a PR:

* Fork the repo.
* If you already did a fork before and submitted a PR, then on "dev" branch just make a git pull.
* Make a local branch out of your target branch (in Quasar's case, all PRs must be done against "dev" branch)
* Make as many commits as necessary, then hit the PR button on Github website.
* I take all your commits, squash them into a single one (full credit goes to you for the changes) and then merge against dev branch.

Tell me if you need help on this. I'm available on Gitter for faster communication.

Cheers,
Razvan

**Comment by dokenzy** [comment]
Thank you for your kindness. I am still confused this PR that includes other's commits. :(
Quasar has a lot of features than other UI framework, I hope quasar will be more popular.

**Comment by smolinari** [comment]
@dokenzy - I am betting it will become a lot more popular. 

Scott

**Pull request closed without merging**
